#解锁新的存储单元需要的权限
permission: "StoreUnits.unlock"
#解锁新的存储单元需要的金币，（注意和升级存储单元的区别）
money: "%unitID%*10"
msg_unlock:
  - '你解锁了新的存储单元'
  - '单元需要%unitID%'
msg_noperm:
  - '你没权限解锁%unitID%号格子'
  - '你需要StoreUnits.%unitID%权限'
#金币不足时消息
msg_nomoney:
  - '你没有足够金币'
  - '无法解锁%unitID%号格子'
#设置单元名字时的发送的提示消息
dialog:
  - "请输入你想要的名字"
  - "在数字前面加&代表颜色代码"
  - "例如: &6代表黄色"
  - "若想取消，请输入“cancel”或“取消”"